TESTV7

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -35,5 +35,13 @@ jobs:
       - name: Run Formatter Check  # Runs Black formatting check
         run: bazel test //:format
 
-      - name: Run Unit Tests  # Run Python unit tests
-        run: bazel test //tests:test_math_utils //tests:test_string_utils
+#      - name: Run Unit Tests  # Run Python unit tests
+#        run: bazel test //tests:test_math_utils //tests:test_string_utils
+      - name: Run Unit Tests
+        run: |
+          bazel test //tests:test_math_utils || (
+            echo "=== TEST LOG START ==="
+            cat /home/runner/.cache/bazel/_bazel_runner/*/execroot/_main/bazel-out/k8-fastbuild/testlogs/tests/test_math_utils/test.log || echo "Log not found"
+            echo "=== TEST LOG END ==="
+            exit 1
+          )
